<a href="https://colab.research.google.com/github/DJ-Manjaray/BERT-Practices/blob/main/BERT_Pre_Training_Masked_Language_Modeling_(MLM).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
from transformers import BertTokenizer, BertForMaskedLM, BertModel, BertConfig

In [3]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


In [55]:
text = ("BERT is an open source machine learning framework for natural language processing (NLP). BERT is designed to help computers understand the meaning of ambiguous language in text by using surrounding text to establish context. The BERT framework was pre-trained using text from Wikipedia and can be fine-tuned with question and answer datasets."

"BERT, which stands for Bidirectional Encoder Representations from Transformers, is based on Transformers, a deep learning model in which every output element is connected to every input element, and the weightings between them are dynamically calculated based upon their connection. In NLP, this process is called attention."

"Historically, language models could only read text input sequentially -- either left-to-right or right-to-left -- but couldn't do both at the same time. BERT is different because it is designed to read in both directions at once. This capability, enabled by the introduction of Transformers, is known as bidirectionality."

"Using this bidirectional capability, BERT is pre-trained on two different, but related, NLP tasks: Masked Language Modeling and Next Sentence Prediction."

"The objective of Masked Language Model (MLM) training is to hide a word in a sentence and then have the program predict what word has been hidden (masked) based on the hidden word's context. The objective of Next Sentence Prediction training is to have the program predict whether two given sentences have a logical, sequential connection or whether their relationship is simply random.")

In [56]:
inputs = tokenizer(text, return_tensors='pt')
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [57]:
inputs.input_ids

tensor([[  101, 14324,  2003,  2019,  2330,  3120,  3698,  4083,  7705,  2005,
          3019,  2653,  6364,  1006, 17953,  2361,  1007,  1012, 14324,  2003,
          2881,  2000,  2393,  7588,  3305,  1996,  3574,  1997, 20080,  2653,
          1999,  3793,  2011,  2478,  4193,  3793,  2000,  5323,  6123,  1012,
          1996, 14324,  7705,  2001,  3653,  1011,  4738,  2478,  3793,  2013,
         16948,  1998,  2064,  2022,  2986,  1011, 15757,  2007,  3160,  1998,
          3437,  2951, 13462,  2015,  1012, 14324,  1010,  2029,  4832,  2005,
          7226,  7442,  7542,  2389,  4372, 16044,  2099, 15066,  2013, 19081,
          1010,  2003,  2241,  2006, 19081,  1010,  1037,  2784,  4083,  2944,
          1999,  2029,  2296,  6434,  5783,  2003,  4198,  2000,  2296,  7953,
          5783,  1010,  1998,  1996,  3635,  8613,  2090,  2068,  2024,  8790,
          3973, 10174,  2241,  2588,  2037,  4434,  1012,  1999, 17953,  2361,
          1010,  2023,  2832,  2003,  2170,  3086,  

In [42]:
inputs.token_type_ids

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0

In [43]:
inputs.attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1

In [44]:
inputs['labels'] = inputs.input_ids.detach().clone()
inputs

{'input_ids': tensor([[  101, 14324,  2003,  2019,  2330,  3120,  3698,  4083,  7705,  2005,
          3019,  2653,  6364,  1006, 17953,  2361,  1007,  1012, 14324,  2003,
          2881,  2000,  2393,  7588,  3305,  1996,  3574,  1997, 20080,  2653,
          1999,  3793,  2011,  2478,  4193,  3793,  2000,  5323,  6123,  1012,
          1996, 14324,  7705,  2001,  3653,  1011,  4738,  2478,  3793,  2013,
         16948,  1998,  2064,  2022,  2986,  1011, 15757,  2007,  3160,  1998,
          3437,  2951, 13462,  2015,  1012, 14324,  1010,  2029,  4832,  2005,
          7226,  7442,  7542,  2389,  4372, 16044,  2099, 15066,  2013,   103,
          1010,  2003,  2241,  2006, 19081,  1010,  1037,  2784,  4083,  2944,
          1999,  2029,  2296,  6434,  5783,  2003,  4198,  2000,  2296,  7953,
          5783,  1010,  1998,  1996,  3635,  8613,  2090,  2068,  2024,  8790,
          3973, 10174,  2241,  2588,  2037,  4434,  1012,  1999, 17953,  2361,
          1010,  2023,  2832,  2003,  

In [45]:
rand = torch.rand(inputs.input_ids.shape)
rand

tensor([[0.2593, 0.5953, 0.1092, 0.3616, 0.9191, 0.7602, 0.2828, 0.3544, 0.6703,
         0.8413, 0.6071, 0.5969, 0.8181, 0.0845, 0.7725, 0.6637, 0.8535, 0.5365,
         0.1595, 0.9534, 0.8764, 0.4509, 0.5654, 0.2474, 0.3124, 0.3676, 0.4600,
         0.6903, 0.7297, 0.3792, 0.0938, 0.9095, 0.7335, 0.5713, 0.4749, 0.6393,
         0.5409, 0.5935, 0.9659, 0.6411, 0.4194, 0.4390, 0.5831, 0.8852, 0.7797,
         0.5904, 0.0456, 0.9076, 0.5134, 0.0423, 0.2761, 0.8279, 0.0642, 0.4280,
         0.7568, 0.3554, 0.4243, 0.1097, 0.7952, 0.7994, 0.4854, 0.1570, 0.2414,
         0.8921, 0.7881, 0.7165, 0.7512, 0.4728, 0.9416, 0.5477, 0.8476, 0.2483,
         0.9728, 0.5492, 0.7185, 0.8530, 0.7051, 0.2152, 0.0684, 0.2448, 0.6838,
         0.3885, 0.0104, 0.9469, 0.6693, 0.2179, 0.7497, 0.2379, 0.0030, 0.0089,
         0.3272, 0.8721, 0.9135, 0.1497, 0.0532, 0.1041, 0.8041, 0.8083, 0.8850,
         0.5733, 0.5523, 0.6481, 0.3930, 0.8381, 0.8101, 0.2649, 0.6598, 0.9785,
         0.3844, 0.3989, 0.2

In [46]:
rand.shape

torch.Size([1, 304])

In [47]:
(inputs.input_ids != 101)

tensor([[False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  

In [48]:
(inputs.input_ids != 102)

tensor([[ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  

In [49]:
mask_array = (rand < 0.15) * (inputs.input_ids != 101) * (inputs.input_ids != 102)
mask_array

tensor([[False, False,  True, False, False, False, False, False, False, False,
         False, False, False,  True, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
          True, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False,  True, False, False,  True,
         False, False,  True, False, False, False, False,  True, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False,  True, False,
         False, False,  True, False, False, False, False, False,  True,  True,
         False, False, False,  True,  True,  True, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False,  True, False, False, False,  True, False,
         False, False, False, False,  True, False,  

In [50]:
mask_array[0]

tensor([False, False,  True, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False,  True,
        False, False,  True, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True, False,
        False, False,  True, False, False, False, False, False,  True,  True,
        False, False, False,  True,  True,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False,  True, False,
        False, False, False, False,  True, False,  True, False, 

In [51]:
mask_array[0].nonzero()

tensor([[  2],
        [ 13],
        [ 30],
        [ 46],
        [ 49],
        [ 52],
        [ 57],
        [ 78],
        [ 82],
        [ 88],
        [ 89],
        [ 93],
        [ 94],
        [ 95],
        [114],
        [118],
        [124],
        [126],
        [134],
        [139],
        [141],
        [149],
        [155],
        [160],
        [170],
        [180],
        [181],
        [199],
        [207],
        [214],
        [216],
        [222],
        [224],
        [229],
        [236],
        [246],
        [253],
        [254],
        [259],
        [263],
        [270],
        [277],
        [291],
        [295],
        [296]])

In [52]:
selection = torch.flatten(mask_array[0].nonzero()).tolist()
selection

[2,
 13,
 30,
 46,
 49,
 52,
 57,
 78,
 82,
 88,
 89,
 93,
 94,
 95,
 114,
 118,
 124,
 126,
 134,
 139,
 141,
 149,
 155,
 160,
 170,
 180,
 181,
 199,
 207,
 214,
 216,
 222,
 224,
 229,
 236,
 246,
 253,
 254,
 259,
 263,
 270,
 277,
 291,
 295,
 296]

In [53]:
inputs.input_ids[0, selection] = 103
inputs.input_ids

tensor([[  101, 14324,   103,  2019,  2330,  3120,  3698,  4083,  7705,  2005,
          3019,  2653,  6364,   103, 17953,  2361,  1007,  1012, 14324,  2003,
          2881,  2000,  2393,  7588,  3305,  1996,  3574,  1997, 20080,  2653,
           103,  3793,  2011,  2478,  4193,  3793,  2000,  5323,  6123,  1012,
          1996, 14324,  7705,  2001,  3653,  1011,   103,  2478,  3793,   103,
         16948,  1998,   103,  2022,  2986,  1011, 15757,   103,  3160,  1998,
          3437,  2951, 13462,  2015,  1012, 14324,  1010,  2029,  4832,  2005,
          7226,  7442,  7542,  2389,  4372, 16044,  2099, 15066,   103,   103,
          1010,  2003,   103,  2006, 19081,  1010,  1037,  2784,   103,   103,
          1999,  2029,  2296,   103,   103,   103,  4198,  2000,  2296,  7953,
          5783,  1010,  1998,  1996,  3635,  8613,  2090,  2068,  2024,  8790,
          3973, 10174,  2241,  2588,   103,  4434,  1012,  1999,   103,  2361,
          1010,  2023,  2832,  2003,   103,  3086,  

In [58]:
outputs = model(**inputs)
outputs

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.5344, -0.6189, -0.2586,  ...,  0.4400, -0.4150,  0.7122],
         [ 0.6019, -0.0820,  0.1610,  ...,  0.5706,  0.5555, -0.1386],
         [-0.8314, -0.2836, -0.1674,  ..., -0.0136, -0.7717,  0.9642],
         ...,
         [ 0.5522, -0.8950,  0.0989,  ..., -0.4885, -0.5068, -0.3868],
         [-0.2382, -0.0602, -0.2001,  ...,  0.2692,  0.0392, -0.6805],
         [-0.4988,  0.1139,  0.3879,  ...,  0.6775, -0.3838,  0.1073]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[ 0.1268,  0.4925,  0.9304, -0.6846, -0.3763,  0.3031, -0.9780, -0.5257,
          0.8248, -0.2527,  0.6266, -0.9237,  0.6398, -0.9127, -0.2507,  0.5358,
          0.8077,  0.3497, -0.2207,  0.9708, -0.6258, -0.9809,  0.6889, -0.1542,
         -0.4968, -0.9893,  0.4781,  0.2413,  0.3579,  0.3581,  0.6038, -0.6049,
         -0.7799,  0.4752,  0.7407,  0.0281, -0.3862,  0.1716,  0.5339,  0.5208,
         -0.2749, -0.2529,  0.84

In [59]:
outputs.keys()

odict_keys(['last_hidden_state', 'pooler_output'])

In [60]:
outputs.last_hidden_state

tensor([[[-0.5344, -0.6189, -0.2586,  ...,  0.4400, -0.4150,  0.7122],
         [ 0.6019, -0.0820,  0.1610,  ...,  0.5706,  0.5555, -0.1386],
         [-0.8314, -0.2836, -0.1674,  ..., -0.0136, -0.7717,  0.9642],
         ...,
         [ 0.5522, -0.8950,  0.0989,  ..., -0.4885, -0.5068, -0.3868],
         [-0.2382, -0.0602, -0.2001,  ...,  0.2692,  0.0392, -0.6805],
         [-0.4988,  0.1139,  0.3879,  ...,  0.6775, -0.3838,  0.1073]]],
       grad_fn=<NativeLayerNormBackward0>)

In [63]:
outputs.pooler_output

tensor([[ 0.1268,  0.4925,  0.9304, -0.6846, -0.3763,  0.3031, -0.9780, -0.5257,
          0.8248, -0.2527,  0.6266, -0.9237,  0.6398, -0.9127, -0.2507,  0.5358,
          0.8077,  0.3497, -0.2207,  0.9708, -0.6258, -0.9809,  0.6889, -0.1542,
         -0.4968, -0.9893,  0.4781,  0.2413,  0.3579,  0.3581,  0.6038, -0.6049,
         -0.7799,  0.4752,  0.7407,  0.0281, -0.3862,  0.1716,  0.5339,  0.5208,
         -0.2749, -0.2529,  0.8422, -0.9749, -0.3167,  0.3272,  1.0000, -0.2530,
         -0.1670, -0.9077, -0.8805, -0.7955, -0.4057, -0.5703, -0.3298,  0.0900,
         -0.7703, -0.5747,  0.2097,  0.4234,  0.0941, -0.5936,  0.8742, -0.1369,
         -0.9265, -0.9110,  0.4503,  0.4621,  0.4311, -0.4377, -0.5561, -0.5174,
          0.5301, -0.1609, -0.8875, -0.0997, -0.9112, -1.0000,  0.6485, -0.6529,
         -0.8356, -0.8892,  0.8699,  0.8757, -0.9352,  1.0000, -0.2592,  0.4583,
         -0.6148, -0.3390, -0.3314,  0.4457, -0.8195,  0.9029,  0.8445,  0.3556,
          0.6026,  0.6041,  